spring:
  config:
    import: optional:configserver:http://localhost:8888/
  cloud:
    config:
      token: roottoken
  application:
    name: user-read-service
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://localhost:5433/my_database
    username: postgres
    password: my_password
server:
  port: 0